version: '3.7'

services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker
      - ~/.docker:/root/.docker:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh:z
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
    environment:
      - TZ=Europe\London
      - DB_URL=mongodb://mongo:27017/petio
    entrypoint: ['zsh', '-c', 'while sleep 1000; do :; done']

  mongo:
    image: mongo:4.4.0
    container_name: 'petio-local-mongo'
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
